### PR TITLE
Fixed crash when Baubles isn't loaded

### PR DESCRIPTION
**Pull request by The-Fireplace**

### CODE REVIEW

**Comment by strikerrocker** [comment]
I dont think this check is necessary as i do this in hasprobebaubles method

**Comment by The-Fireplace** [comment]
Honestly, this PR was a quick and lazy fix to the problem anyways. I'm not
going to make a proper fix for the issue for you, but I will explain the
problem, and how I learned to solve it. Right now, you are directly
accessing code from Baubles API in your mod's code. This means without
Baubles loaded, it crashes. What you need to do is access the Baubles code
using an interface, rather than directly accessing it. So for example:
Make an interface called IBaublesCompat. In it, add methods for everything
you want to do with Baubles.
Make 2 classes implementing this interface. One class that interacts with
Baubles like you're doing now, and another class that's a dummy file. You
can leave all the methods empty or put alternate code in to be run if you
like. Do not interact with Baubles code in this file.
Next step: Anytime you want to use the methods involving Baubles, you would
create an IBaublesCompat object, then, if baubles is loaded, set it equal
to an instance of the actual Baubles interaction class. If not, set it
equal to an instance of the dummy class. Then call the methods from that
object.
Does that make sense? I can provide code examples from when I've done it in
the past, if needed.

On Feb 4, 2018 8:20 PM, "Striker Rocker" <notifications@github.com> wrote:

Closed #22 <https://github.com/strikerrocker/VanillaTweaks/pull/22>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/strikerrocker/VanillaTweaks/pull/22#event-1457111919>,
or mute the thread

**Comment by strikerrocker** [comment]
Can u provide me code examples

**Comment by strikerrocker** [comment]
does this PR actually work out?

**Comment by The-Fireplace** [comment]
Well, maybe. I wouldn't trust the method I used in this PR, it was a quick, untested bandaid to the real problem.

**Comment by The-Fireplace** [comment]
As far as code examples, you'll want to do something like I did to add Chisel integration to Fire's Random Things.
[The interface and the classes extending it](https://github.com/The-Fireplace-Minecraft-Mods/Fires-Random-Things/tree/master/src/main/java/the_fireplace/frt/compat/chisel)
[How to use that interface](https://github.com/The-Fireplace-Minecraft-Mods/Fires-Random-Things/blob/master/src/main/java/the_fireplace/frt/items/ItemObsidianBreaker.java#L52-L57)

**Comment by The-Fireplace** [comment]
If you have more questions, you can message on Discord. I'm on Minecraft Mod Dev, and [my own Discord server](https://discord.gg/CJUBWRH).

**Pull request closed without merging**
